title: "NurseyBook"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: GML

repository: "AY2122S1-CS2103T-F13-2/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
